# Generated by Django 6.0.3 on 2026-03-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('position_title', models.CharField(blank=True, max_length=120, null=True)),
                ('is_enron_employee', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['employee_key'],
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('local_part', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_addresses', to='enron.collaborator')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_root_path', models.CharField(blank=True, help_text='Chemin racine du maildir source, ex: /app/data/enron/maildir/allen-p', max_length=1024, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='enron.collaborator')),
            ],
            options={
                'ordering': ['mailbox_key'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_path', models.CharField(max_length=500)),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_type', models.CharField(blank=True, max_length=50, null=True)),
                ('folder_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='enron.mailbox')),
            ],
            options={
                'ordering': ['mailbox', 'folder_path'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('sender_email', models.CharField(blank=True, db_index=True, max_length=320, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('subject_normalized', models.TextField(blank=True, null=True)),
                ('body_clean', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type_header', models.CharField(blank=True, max_length=500, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('parse_ok', models.BooleanField(default=True)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('is_response', models.BooleanField(default=False)),
                ('is_forward', models.BooleanField(default=False)),
                ('response_to_message_id', models.CharField(blank=True, max_length=500, null=True)),
                ('response_to_message_id_source', models.CharField(blank=True, max_length=100, null=True)),
                ('thread_root_message_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('references_depth', models.PositiveIntegerField(default=0)),
                ('quoted_line_count', models.PositiveIntegerField(default=0)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='enron.emailaddress')),
            ],
            options={
                'ordering': ['-sent_at', 'message_id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='enron.message')),
            ],
            options={
                'ordering': ['message', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message_links', to='enron.emailaddress')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='enron.message')),
            ],
            options={
                'ordering': ['message', 'recipient_type', 'email_address', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referenced_message_id', models.CharField(db_index=True, max_length=500)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_references', to='enron.message')),
            ],
            options={
                'ordering': ['message', 'referenced_message_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['email'], name='enron_email_email_e04ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['domain'], name='enron_email_domain_aeebac_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['local_part'], name='enron_email_local_p_7ce292_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['collaborator'], name='enron_email_collabo_35edf1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['domain', 'local_part'], name='enron_email_domain_08a0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['mailbox_key'], name='enron_mailb_mailbox_b29515_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['owner'], name='enron_mailb_owner_i_53ba64_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['mailbox', 'folder_type'], name='enron_folde_mailbox_37ae52_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['mailbox', 'folder_name'], name='enron_folde_mailbox_7c3210_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['mailbox', 'folder_path'], name='enron_folde_mailbox_8f0687_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('mailbox', 'folder_path'), name='uq_folder_mailbox_path'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='enron_messa_sent_at_18de4f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_email'], name='enron_messa_sender__7946a6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_root_message_id'], name='enron_messa_thread__e46181_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['in_reply_to'], name='enron_messa_in_repl_db24be_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message'], name='enron_attac_message_4badad_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['sha256'], name='enron_attac_sha256_433e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['message', 'recipient_type'], name='enron_messa_message_0a9f06_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['email_address'], name='enron_messa_email_a_269314_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagerecipient',
            constraint=models.UniqueConstraint(fields=('message', 'email_address', 'recipient_type'), name='uq_message_recipient_per_type'),
        ),
        migrations.AddIndex(
            model_name='messagereference',
            index=models.Index(fields=['message'], name='enron_messa_message_73aa97_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereference',
            index=models.Index(fields=['referenced_message_id'], name='enron_messa_referen_c518b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereference',
            constraint=models.UniqueConstraint(fields=('message', 'referenced_message_id'), name='uq_message_reference'),
        ),
    ]
