# Generated by Django 6.0.3 on 2026-03-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(max_length=1024, unique=True)),
                ('validation_is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_occurrences', to='enron.folder')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_occurrences', to='enron.mailbox')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='enron.message')),
            ],
            options={
                'indexes': [models.Index(fields=['mailbox', 'folder'], name='enron_messa_mailbox_6489eb_idx'), models.Index(fields=['message'], name='enron_messa_message_ef4594_idx'), models.Index(fields=['mailbox', 'message'], name='enron_messa_mailbox_7bbb24_idx')],
            },
        ),
    ]
