# Generated by Django 6.0.3 on 2026-03-16 11:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0002_messageoccurrence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    django.db.models.functions.comparison.Coalesce(
                        'subject_normalized',
                        models.Value('', output_field=models.TextField()),
                        output_field=models.TextField(),
                    ),
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.functions.text.Left('body_clean', 200000),
                        models.Value('', output_field=models.TextField()),
                        output_field=models.TextField(),
                    ),
                    config='english',
                ),
                name='message_fts_gin_idx',
            ),
        ),
    ]