# Generated by Django 6.0.3 on 2026-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0003_message_message_fts_gin_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at', 'id']},
        ),
        migrations.AddField(
            model_name='message',
            name='canonical_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_root_message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='enron_messa_message_4bb0a2_idx'),
        ),
    ]
