# Generated by Django 6.0.3 on 2026-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0004_alter_message_options_message_canonical_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_html_clean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
